# Generated by Django 4.0.3 on 2022-03-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('subtitle', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=56)),
                ('isbn', models.CharField(max_length=20)),
            ],
        ),
    ]
